### ISSUE TITLE
Self closed XML nodes causes out of memory / segfault

### ISSUE THREAD

**Issue by xar** [sergiorodenas/stream-parser#25]
When the XML file contains self-closing tags like `<Test name="name" value="OOM" />` . The parser will end in infinite loop and crash the fpm process.

**Comment by keradan** [comment]
> When the XML file contains self-closing tags like `<Test name="name" value="OOM" />` . The parser will end in infinite loop and crash the fpm process.

Same problem... Did you find the solution?

**Comment by NetFix1** [comment]
$emptyElement = $this->isEmptyElement($elementName);

		$elementCollection = (new Collection())->merge($this->getCurrentElementAttributes());

		if($emptyElement) {
			return $elementCollection;
		}

**Comment by sergiorodenas** [comment]
Fixed in https://github.com/sergiorodenas/stream-parser/pull/34
