### ISSUE TITLE
How to install package 

### ISSUE THREAD

**Issue by guntisluta** [sergiorodenas/stream-parser#32]
Hi!
Sorry for my stupid question, but what is correct way to install your package.

I use Laravel 5.6 
I put this in use block  in head
use Tightenco\Collect\Support\Collection;

In code I write
StreamParser::xml(storage_path('app').'/file.xml')->each(function(Collection $product){
		    var_dump($product);
		});

and I have error
In.........php line 80:
  Class 'App\Console\Commands\StreamParser' not found

**Comment by michaelcozzolino** [comment]
#19 as stated here just import it like this:
use Rodenastyle\StreamParser\StreamParser;
